apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "varnish-gateway.namespace" . }}
  labels:
    {{- include "varnish-gateway.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
